site_name: Enterprise Architecture Docs

nav:
  - Home: index.md
  - Arquitetura: arquitetura.md
  - Repositórios: repositórios.md
  - Padrões de Desenvolvimento: padrões-dev.md
  - CI/CD: ci-cd.md
  - Segurança: segurança.md
  - Observabilidade: observabilidade.md
  - Roadmap: roadmap.md

site_url: https://dudxtec.github.io/enterprise-architecture/
use_directory_urls: false
